---
- name: apply the common configuration to all hosts
  hosts: all

  roles:
  - common

- name: apply the httpd
  hosts: web

  roles:
  - httpd
  - web

- name: apply the database configuration
  hosts: db

  roles:
  - mariadb
