---
- name: install httpd
  yum: name=httpd state=latest

- name: create sites directories
  file: path=/var/www/html/sites state=directory
  # with_items: "{{ httpd_dirs }}"

- name: copy an index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

- name: create directory sites_enabled
  file: name=/etc/httpd/conf/sites-enabled state=directory

- name: copy httpd configuration
  template: src=httpd.conf-{{ ansible_os_family }}.j2 dest=/etc/httpd/conf/httpd.conf
  notify: restart httpd

- name: start httpd service
  service: name=httpd state=started enabled=yes
